// <auto-generated />
using System;
using FeedbackSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241020175858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedbackSystem.Models.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Atque sit autem.",
                            CreatedAt = new DateTime(2023, 12, 7, 3, 35, 19, 284, DateTimeKind.Local).AddTicks(4932),
                            CustomerId = 1,
                            ProductId = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Placeat quia sit sint.",
                            CreatedAt = new DateTime(2023, 11, 5, 20, 48, 54, 971, DateTimeKind.Local).AddTicks(5858),
                            CustomerId = 2,
                            ProductId = 0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Et labore repellat corporis iusto et.",
                            CreatedAt = new DateTime(2024, 5, 29, 4, 22, 40, 441, DateTimeKind.Local).AddTicks(2945),
                            CustomerId = 3,
                            ProductId = 0,
                            Rating = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Aperiam totam officiis corrupti beatae recusandae ea et.",
                            CreatedAt = new DateTime(2024, 4, 11, 14, 11, 38, 195, DateTimeKind.Local).AddTicks(7994),
                            CustomerId = 4,
                            ProductId = 0,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Nam qui eius voluptate et reprehenderit quis ipsum voluptas.",
                            CreatedAt = new DateTime(2024, 4, 4, 6, 1, 11, 660, DateTimeKind.Local).AddTicks(5611),
                            CustomerId = 5,
                            ProductId = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Consequatur qui rerum facilis minus velit doloremque architecto nobis est.",
                            CreatedAt = new DateTime(2024, 8, 23, 18, 39, 30, 635, DateTimeKind.Local).AddTicks(9388),
                            CustomerId = 6,
                            ProductId = 0,
                            Rating = 1
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Accusamus earum aperiam ut dolorum fuga.",
                            CreatedAt = new DateTime(2024, 6, 22, 23, 52, 41, 258, DateTimeKind.Local).AddTicks(9616),
                            CustomerId = 7,
                            ProductId = 0,
                            Rating = 1
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Iure minima reprehenderit laborum esse quo recusandae delectus quos consequuntur.",
                            CreatedAt = new DateTime(2024, 4, 17, 21, 19, 5, 923, DateTimeKind.Local).AddTicks(2038),
                            CustomerId = 8,
                            ProductId = 0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Accusamus fuga mollitia est soluta similique sunt velit.",
                            CreatedAt = new DateTime(2024, 8, 13, 9, 3, 5, 761, DateTimeKind.Local).AddTicks(839),
                            CustomerId = 9,
                            ProductId = 0,
                            Rating = 5
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Ducimus ut ut qui blanditiis debitis omnis et.",
                            CreatedAt = new DateTime(2024, 6, 6, 4, 26, 53, 2, DateTimeKind.Local).AddTicks(7078),
                            CustomerId = 10,
                            ProductId = 0,
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
